import ReactQueryClientProvider from "@/components/providers/ReactQueryClientProvider";
import { Toaster } from "@/components/ui/toaster";
import { poppins } from "@/ui/fonts/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={`${poppins.variable} antialiased`}
        >
          {children}
          <Toaster />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
